#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# python manage.py makemigrations
python manage.py migrate

# if [ "$DJANGO_SUPERUSER_USERNAME" ]
# then
#     python manage.py createsuperuser \
#         --noinput \
#         --username $DJANGO_SUPERUSER_USERNAME \
#         --email $DJANGO_SUPERUSER_EMAIL
# fi

# $@

exec python manage.py runserver_plus 0.0.0.0:8000
