#!/bin/bash
set -o errexit
set -o pipefail
set -o nounset

# Run migrations
python manage.py makemigrations
python manage.py migrate

# Collect static files (important for production)
python manage.py collectstatic --noinput

# Start Gunicorn
exec gunicorn wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 120