version: '3'

volumes:
  biocrust_app_local_postgres_data: {}
  biocrust_app_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: biocrust_app_local_django
    container_name: biocrust_app_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
      - ./.envs/.local/.redis
    ports:
      - '8000:8000'
    command: /start


  ml-api:
    build:
      context: .
      dockerfile: ./compose/local/ml-api/Dockerfile
    env_file:
      - ./.envs/.local/.ml-api
      - ./.envs/.local/.redis
    image: biocrust_app_local_ml-api
    container_name: biocrust_app_local_ml-api
    depends_on:
      - postgres
    ports:
      - "8082:8082"

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: biocrust_app_production_postgres
    container_name: biocrust_app_local_postgres
    volumes:
      - biocrust_app_local_postgres_data:/var/lib/postgresql/data
      - biocrust_app_local_postgres_data_backups:/backups
    ports:
      - '5432:5432'
    env_file:
      - ./.envs/.local/.postgres

  # docs:
  #   image: biocrust_app_local_docs
  #   container_name: biocrust_app_local_docs
  #   build:
  #     context: .
  #     dockerfile: ./compose/local/docs/Dockerfile
  #   env_file:
  #     - ./.envs/.local/.django
  #   volumes:
  #     - ./docs:/docs:z
  #     - ./config:/app/config:z
  #     - ./biocrust_app:/app/biocrust_app:z
  #   ports:
  #     - '9000:9000'
  #   command: /start-docs

  frontend:
    container_name: frontend
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: biocrust_app_frontend
    depends_on:
      - django
    volumes:
      - ./frontend/nginx:/etc/nginx/conf.d
    ports:
      - '81:80'

  redis:
    build:
      context: .
      dockerfile: ./compose/local/redis/Dockerfile
    image: biocrust_app_production_redis
    container_name: biocrust_app_redis
    restart: unless-stopped
    env_file:
      - ./.envs/.local/.redis
    volumes:
      - ./redis_data:/data
    ports:
      - "6379:6379"
  
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: biocrust_app_redis_commander
    restart: unless-stopped
    env_file:
      - ./.envs/.local/.redis-commander
      - ./.envs/.local/.redis
    ports:
      - "8081:8081"
    depends_on:
      - redis

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: biocrust_app_local_pgadmin
  #   depends_on:
  #     - postgres
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@mail.com
  #     - PGADMIN_DEFAULT_PASSWORD=admin
  #     - PGADMIN_LISTEN_PORT=5050
  #   ports:
  #     - '5050:5050'
  #   volumes:
  #     - biocrust_app_local_postgres_data:/var/lib/postgresql/data
  #     - biocrust_app_local_postgres_data_backups:/backups

