
api:
  dashboard: true
  debug: true

log:
  level: INFO

entryPoints:
  http:
    address: ':80'
  https:
    address: ':443'
serversTransport:
  insecureSkipVerify: true
providers:
  docker:
    endpoint: 'unix:///var/run/docker.sock'
    exposedByDefault: false
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
certificatesResolvers:
  cloudflare:
    acme:
      email: 'philipp.faulhammer@gmail.com'
      storage: /etc/traefik/acme/acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - '1.1.1.1:53'
          - '1.0.0.1:53'


