
api:
  dashboard: true
  debug: true

log:
  level: INFO

entryPoints:
  http:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  https:
    address: ':443'
    http:
      tls:
        certResolver: cloudflare

certificatesResolvers:
  cloudflare:
    acme:
      email: 'philipp.faulhammer@gmail.com'
      storage: /etc/traefik/acme/acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - '1.1.1.1:53'
          - '1.0.0.1:53'


providers:
  docker:
    exposedByDefault: false

# services:
#   frontend:
#     loadBalancer:
#       servers:
#         - url: http://frontend:80

# serversTransport:
#   insecureSkipVerify: true
# providers:
#   docker:
#     endpoint: 'unix:///var/run/docker.sock'
#     exposedByDefault: false
#   file:
#     filename: /etc/traefik/traefik.yml
#     watch: true




