
api:
  dashboard: true
  debug: true

log:
  level: INFO

entryPoints:
  http:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ':443'
    http:
      tls:
        certificates:
          - certFile: /etc/traefik/certs/fullchain.pem
            keyFile: /etc/traefik/certs/privkey.pem


providers:
  docker:
    exposedByDefault: false

# services:
#   frontend:
#     loadBalancer:
#       servers:
#         - url: http://frontend:80

# serversTransport:
#   insecureSkipVerify: true
# providers:
#   docker:
#     endpoint: 'unix:///var/run/docker.sock'
#     exposedByDefault: false
#   file:
#     filename: /etc/traefik/traefik.yml
#     watch: true